### ISSUE TITLE
Search suggestions are encoded (when the search string is not in English)

### ISSUE THREAD

**Issue by YakovL** [Sangwan5688/BlackHole#577]
**Describe the bug**
In the YouTube tab, typing a search query in a language other than English results in the encoded search suggestions (see the screenshots below).

**Steps To Reproduce**

1. Open the YouTube tab
2. Start typing in the search input, for instance "სა" (ge) or "испанский" (ru). Pasting will also reproduce this.

**Expected behavior**
The search suggestions should be displayed normally, like "საქართველო".

**Actual behavior**

The suggestions are instead encoded, like "&#4321;&#4304;...". Here are a couple of screenshots:

![image](https://github.com/Sangwan5688/BlackHole/assets/1131924/8147dd2c-21e1-46d7-a78b-fa8d3a97cca9)
![image](https://github.com/Sangwan5688/BlackHole/assets/1131924/6f96fd43-13e8-479a-85a4-4185600dfd04)

**Device Details (please complete the following information):**
 - OS: Android 10
 - Device: Armor X7 Pro
 - App Version: 1.15.5 (looks like it's the latest in F-Droid, although I can see that the latest release here is 1.15.7)
   - after updating to 1.15.7, the bug is still there (but the log below is for 1.15.5)

**App Logs:**

SEVERE: 2023-05-13 22:53:01.695077: record.message: Error in getMusicHome: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("contents")
record.error: null
record.stackTrace: null

**Comment by YakovL** [comment]
@ankit-sa thanks for the fix! Looking forward to see the new version :)
